# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

auth:
  orchSvcs:
    roleMaxTTL: 1h
  oidc:
    idPAddr: "https://keycloak.vedge.dev.vivega.ai"
    idPDiscoveryURL: "https://keycloak.vedge.dev.vivega.ai/realms/master"
    roleMaxTTL: 1h
